name: hairtech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  fl_chart: ^0.69.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  flutter_localization: ^0.3.3
  camera: ^0.11.2+1
  image: ^4.5.4
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  sensors_plus: ^7.0.0
  flutter_tts: ^3.8.5
  video_player: ^2.10.1
  google_mlkit_pose_detection: ^0.14.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter-BlackItalic.otf
          weight: 900
          style: italic